FROM val-dev
COPY val_0.0.0.9000.tar.gz /
RUN R -e "devtools::install_local('/val_0.0.0.9000.tar.gz');"
COPY scripts/cli.R /usr/bin/validate
RUN chmod --reference=/bin/bash /usr/bin/validate
RUN chown --reference=/bin/bash /usr/bin/validate
CMD /bin/bash
